### ISSUE TITLE
relation-dsl: relationProject oddity

### ISSUE THREAD

**Issue by SolalPirelli** [epfldata/sc-public#12]
In `RelationLowering`, `relationProject` is called with the same argument for the old and new schema; was the 3rd argument [here](https://github.com/epfldata/sc-public/blob/e8596325941619150c8c16a74ee4f4d73bb27750/relation-dsl/relation-deep/src/main/scala/relation/compiler/RelationLowering.scala#L74) meant to be `schema1`?

Also, in `RecordsLowering`, it appears the code is completely ignoring the new schema and simply copying every tuple, which seems to defeat the purpose of a projection...?

**Comment by LPTK** [comment]
This is a minor oversight on our side: there should only be one Schema parameter to the `relationJoin` function: the final schema. Currently, we pass the **_final_** schema twice.
So the code in `RecordsLowering` that uses the first parameter behaves correctly, and is in fact doing a rightful projection (you can verify this by running [`pgrmA`](https://github.com/epfldata/sc-public/blob/e8596325941619150c8c16a74ee4f4d73bb27750/relation-dsl/relation-deep/src/main/scala/relation/compiler/Main.scala#L11)).
