### ISSUE TITLE
Make a tutorial about staging

### ISSUE THREAD

**Issue by LPTK** [epfldata/sc-public#9]
And provide a way to run `dsl` code, as requested by W.T..

**Comment by LPTK** [comment]
There is now [a short document](https://github.com/epfldata/sc-public/blob/master/doc/MSP-QQ.md) about staging and quasiquotes, and the [new quasiquotes project](https://github.com/LPTK/SC-Paradise-Open-Terms-Proto) does have a proper `run`.

**Comment by amirsh** [comment]
👍
